version: '3'

services:

  # MariaDB Setup
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/noerkel/bs14-itech/scooter/documentatio/sql/scooter-gmbh.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scooter
    env_file:
      - ./backend/.env

  # Simple UI for Database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - scooter

  # Start the Backendserver, who hosted the frontend
  fullstack:
    image: docker.autonubil.net/schule/scootec-gmbh/backend
    restart: always
    ports:
      - 10000:10000
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - adminer
    networks:
      - scooter

    # Prometheus
  
  # Prometheus
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    stdin_open: true
    tty: true
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - db
      - adminer
      - fullstack
    networks:
      - scooter

  # Grafana 
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
    networks:
      - scooter 

networks:
  scooter:
