version: '3'

services:

  # MariaDB Setup
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql/noerkelit_chat.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat
    env_file:
      - ./backend/.env

  # Simple UI for Database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - chat

  # Start the Backendserver, who hosted the frontend
  fullstack:
    image: Docker.autonubil.net/noerkelit/chat/backend
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - adminer
      - minioserver
    networks:
      - chat

networks:
  chat:
