version: '3'

services:

  # MariaDB Setup
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql/scooter-gmbh.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scooter
    env_file:
      - ./backend/.env

  # Simple UI for Database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - scooter

  # Start the Backendserver, who hosted the frontend
  fullstack:
    image: docker.autonubil.net/schule/scootec-gmbh/backend
    restart: always
    ports:
      - 10000:10000
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - adminer
      - prometheus
    networks:
      - scooter

    # Prometheus
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    stdin_open: true
    tty: true
    env_file:
      - ./config/prometheus/prometheus.yml
    depends_on:
      - db
      - adminer
    networks:
      - fullstack

  # Grafana 
  prometheus:
    image: grafana/grafana
    restart: always
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    env_file:
      - ./config/grafana/datasources.yml
    depends_on:
      - db
      - adminer
    networks:
      - prometheus 

networks:
  scooter:
