apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://documentatio-prometheus-1:9090
    basicAuth: false
    isDefault: true
    editable: true
providers:
  - name: dashboards
    type: file
    updateIntervalSeconds: 30
    options:
      path: ./dashboards
      foldersFromFilesStructure: true