global:
  scrape_interval: 5s
scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["localhost:9090"]
- job_name: "backend"
  static_configs:
  - targets: ["documentatio-fullstack-1:9100"]
- job_name: "scooter"
  http_sd_configs: 
    - url: "http://documentatio-fullstack-1:9100/jobs"


